### ISSUE TITLE
Problem with created a new user and database

### ISSUE THREAD

**Issue by mdcostas** [martikainen87/Home-Automation#1]
Hello,

The first thing is to thank you for the guide you have done.

I have followed all the steps, but in the part of the database I have completely lost, I do not know how to do what you indicate:

"Since I'm running MySQL in docker I created a new user and database called homeassistant using PhpMyAdmin."

I do not know if you could tell me how to do this.

Again thank you very much.

Regards.

PS: I do not think this is the appropriate place for this consultation, but I did not find how to contact you.

**Comment by martikainen87** [comment]
Hi

Sorry i totally missed this part! What I've found is that newer versions of mysql doesnt work, think anything after 6.x is broken. 
If ur running hass.io I would recommend to use the addon "mariaDB"
